### ISSUE TITLE
Command burst CPU and grid requirement are not calculated

### ISSUE THREAD

**Issue by Slivo-fr** [Slivo-fr/EveHQ#127]
Somehow, the calculation of CPU and grid does not include command burst modules :o

**Comment by Slivo-fr** [comment]
We might have been a bit too agressive in BuildModuleEffects (fitting.vb line 1200)

**Comment by Slivo-fr** [comment]
Seems related to change from #124 
You filtered every effect from command burst, CPU and grid included.
Any chance to change the filter to only affect the boost effect @dukrat ?

**Comment by dukrat** [comment]
I could perhaps have done that by hardcoding in all the group effects, but I wanted it to be better than that.   Unfortunately, allowing the local bursts to have all their effects by slightly changing the if statement there wasn't possible.  The issue with this whole section is that the bursts should only apply to the charge they have loaded.  I have now implemented this by recording the module that caused a final effect and filtering off of that.  Additionally, because of the way module/charge effects are calculated for remote ships it is necessary to filter out all but gang effects from other ships otherwise you get the effect twice if the module is active on the remote ship.  You can't just get rid of the gang effects in the csv though, because that requires the burst to be active on the remote ship for it to work which is a pain.  I'm heavily commented the special handling so it hopefully should be understandable now.  

The way filtering the burst effects has changed.  All aspects should be retested but only testing a single local remote pair and burst type should be okay.  (https://github.com/Slivo-fr/EveHQ/issues/130)

**Comment by Slivo-fr** [comment]
Thanks you ! Need some testing before releasing a minor update

**Comment by Slivo-fr** [comment]
Fix testing looks fine for me. Thanks !
